// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbBt0MId0fA2ekTjZ43QU1o_BJcloskCM',
    appId: '1:426772719419:web:bb523445d944f7975d391e',
    messagingSenderId: '426772719419',
    projectId: 'socialapptutorialreview',
    authDomain: 'socialapptutorialreview.firebaseapp.com',
    storageBucket: 'socialapptutorialreview.firebasestorage.app',
    measurementId: 'G-3M0R9MZG95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXZcdf1GqfVZlZ6iCMs_yfMCW4lNVcE8E',
    appId: '1:426772719419:android:b1b5821f162e260e5d391e',
    messagingSenderId: '426772719419',
    projectId: 'socialapptutorialreview',
    storageBucket: 'socialapptutorialreview.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaEgvIDnAnBwiREMesEDKqJWD9t5QUuok',
    appId: '1:426772719419:ios:5271f785ea671fe55d391e',
    messagingSenderId: '426772719419',
    projectId: 'socialapptutorialreview',
    storageBucket: 'socialapptutorialreview.firebasestorage.app',
    iosBundleId: 'com.example.projet1Review',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaEgvIDnAnBwiREMesEDKqJWD9t5QUuok',
    appId: '1:426772719419:ios:5271f785ea671fe55d391e',
    messagingSenderId: '426772719419',
    projectId: 'socialapptutorialreview',
    storageBucket: 'socialapptutorialreview.firebasestorage.app',
    iosBundleId: 'com.example.projet1Review',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbBt0MId0fA2ekTjZ43QU1o_BJcloskCM',
    appId: '1:426772719419:web:274b833398c38c585d391e',
    messagingSenderId: '426772719419',
    projectId: 'socialapptutorialreview',
    authDomain: 'socialapptutorialreview.firebaseapp.com',
    storageBucket: 'socialapptutorialreview.firebasestorage.app',
    measurementId: 'G-1VC9S60VYP',
  );
}
